openapi: 3.0.3
info:
  title: modulos-promocionales-api
  description: Microservicio de gestion de peticiones de Informacion e inyeccion de
    Datos
  version: 1.0.11
servers:
- url: /rest/modulos-promocionales-api/v1.0/
tags:
- name: Lugares
  description: "Informacion de Provincias, Ciudades, Sectores y Zonas donde aplican\
    \ los modulos."
- name: Financiero
  description: "Informacion de datos financieron como Modos de Pago, buro, y datos\
    \ promocionales que aplican en los modulos."
- name: Planes
  description: Informacion de datos sobre planes sobre productos de modulos.
- name: Modulo Promocional
  description: Carga de Modulo Promocional
paths:
  /get/lugares/provincias:
    post:
      tags:
      - Lugares
      description: Consulta de Datos de Provincias segun sus parametros.
      operationId: get_provincias
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetProvincia'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetProvincia_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.lugares_controller
  /get/lugares/ciudades:
    post:
      tags:
      - Lugares
      description: Consulta de Datos de Ciudades
      operationId: get_ciudades
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetCiudades'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetCiudad_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.lugares_controller
  /get/lugares/sectores:
    post:
      tags:
      - Lugares
      description: Consulta de Datos de Sectores
      operationId: get_sectores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetSectores'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetSectores_Data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.lugares_controller
  /get/planes/ofertas:
    post:
      tags:
      - Planes
      description: Consulta de Datos de Ofertas
      operationId: get_ofertas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetOfertas'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfertas_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.planes_controller
  /get/planes/servicios:
    post:
      tags:
      - Planes
      description: Consulta de Datos de Servicios
      operationId: get_servicios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetServicios'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseServicios_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.planes_controller
  /get/planes/combos:
    post:
      tags:
      - Planes
      description: Consulta de Datos de Combos
      operationId: get_combos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetCombos'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCombos_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.planes_controller
  /get/planes/planes:
    post:
      tags:
      - Planes
      description: Consulta de Datos de Planes
      operationId: get_planes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetPlanes'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetPlanes_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.planes_controller
  /get/finance/buro:
    post:
      tags:
      - Financiero
      description: Consulta de Buro
      operationId: get_buro
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetBuro'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetBuro_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /get/finance/modos-pago:
    post:
      tags:
      - Financiero
      description: Consulta de Modos de Pago
      operationId: get_modospago
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetFormasPago'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetFormasPago_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /get/finance/dias-gozados:
    post:
      tags:
      - Financiero
      description: Consulta de Dias Gozados
      operationId: get_diasgozados
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetDiasGozados'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetDiasGozados_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /get/finance/upgrade:
    post:
      tags:
      - Financiero
      description: Consulta de Datos Upgrade
      operationId: get_upgrade
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetUpgrade'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetUpgrade_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /get/finance/precio-regular:
    post:
      tags:
      - Financiero
      description: Consulta de Precios de Productos
      operationId: get_precioregular
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetPrecioRegular'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetPrecioRegular_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /post/modulo-promocional:
    post:
      tags:
      - Modulo Promocional
      description: Envio de Datos a Base de Datos
      operationId: post_modulopromocional
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResquestPostDiccionarioDatos'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePostDiccionarioDatos_data'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      x-openapi-router-controller: swagger_server.controllers.modulo_promocional_controller
components:
  schemas:
    RequestGetProvincia:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_PROVS
        TARIFFPLANVARIANT:
          type: integer
          example: 200
    RequestGetCiudades:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_PROVS
        id_Prov:
          type: integer
          example: 12123
        id_Provs:
          type: array
          example:
          - 12123
          - 45678
          - 78901
          items:
            type: integer
        TARIFFPLANVARIANT:
          type: integer
          example: 200
        PRODUCTOID:
          type: integer
          example: 200
    RequestGetSectores:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_SECTORS
        id_City:
          type: integer
          example: 12123
        id_Cities:
          type: array
          example:
          - 12123
          - 45678
          - 78901
          items:
            type: integer
        TARIFFPLANVARIANT:
          type: integer
          example: 200
        PRODUCTOID:
          type: integer
          example: 200
    RequestGetPlanes:
      required:
      - channel
      - stype
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
        stype:
          type: string
          example: AD_
        SERVICIO:
          type: string
          example: INTERNET
        TIPO_SERVICIO:
          type: string
          example: RESIDENCIAL
    RequestGetServicios:
      required:
      - channel
      - stype
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
        stype:
          type: string
          example: AD_
    RequestGetOfertas:
      required:
      - channel
      - stype
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
        stype:
          type: string
          example: AD_
    RequestGetCombos:
      required:
      - channel
      - stype
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
        stype:
          type: string
          example: AD_
        _V1:
          type: string
          example: Puede ser Numero o Palabra pero no 2 a la vez
    RequestGetBuro:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
    RequestGetFormasPago:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
    RequestGetDiasGozados:
      required:
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
    RequestGetPrecioRegular:
      required:
      - TARIFFPLANVARIANT
      - channel
      - id_Prod
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ' ALL_'
        TARIFFPLANVARIANT:
          type: integer
          example: 128213
        id_Prod:
          type: integer
          example: 128213
    RequestGetUpgrade:
      required:
      - TARIFFPLAN
      - TARIFFPLANVARIANT
      - channel
      - type
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        type:
          type: string
          example: ALL_
        TARIFFPLAN:
          type: integer
          example: 8909
        TARIFFPLANVARIANT:
          type: integer
          example: 128213
    ResquestPostDiccionarioDatos:
      required:
      - channel
      - diccionarioDatos
      properties:
        channel:
          type: string
          example: web-modulos-promocionales
        diccionarioDatos:
          $ref: '#/components/schemas/DiccionarioDatos'
    ResponseGetProvincia_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        PROVINCIES:
          $ref: '#/components/schemas/ResponseGetProvincia_data_PROVINCIES'
      example:
        PROVINCIES:
          PROVINCIA: PROVINCIA
          PROVINCIA_ID: 0
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetCiudad_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        CITIES:
          $ref: '#/components/schemas/ResponseGetCiudad_data_CITIES'
        CITIESxPROV:
          $ref: '#/components/schemas/ResponseGetCiudad_data_CITIES'
      example:
        errorCode: 0
        CITIES:
          PROVINCIA: PROVINCIA
          CIUDAD: CIUDAD
          CIUDAD_ID: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
        CITIESxPROV: null
    ResponseGetSectores_Data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        SECTORS:
          $ref: '#/components/schemas/ResponseGetSectores_Data_SECTORS'
        SECTORSxCITY:
          $ref: '#/components/schemas/ResponseGetSectores_Data_SECTORS'
      example:
        SECTORSxCITY: null
        SECTORS:
          SECTOR: SECTOR
          CIUDAD: CIUDAD
          SECTOR_ID: 0
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetPlanes_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        PLANES:
          $ref: '#/components/schemas/ResponseGetPlanes_data_PLANES'
      example:
        PLANES:
          TARIFFPLANID: 0
          TARIFFPLANVARIANT: TARIFFPLANVARIANT
          TARIFFPLAN: TARIFFPLAN
          TARIFFPLANVARIANTID: 6
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseServicios_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        SERVICIOS:
          $ref: '#/components/schemas/ResponseServicios_data_SERVICIOS'
      example:
        SERVICIOS:
          SERVICIOS: SERVICIOS
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseOfertas_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        OFERTAS:
          $ref: '#/components/schemas/ResponseOfertas_data_OFERTAS'
      example:
        OFERTAS:
          OFERTA_ID: 0
          OFERTA: OFERTA
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseCombos_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        COMBO_PLAN:
          $ref: '#/components/schemas/ResponseCombos_data_COMBO_PLAN'
        COMBO_PLANVARIANT:
          $ref: '#/components/schemas/ResponseCombos_data_COMBO_PLANVARIANT'
        COMBO_PRODUCTO:
          $ref: '#/components/schemas/ResponseCombos_data_COMBO_PRODUCTO'
      example:
        COMBO_PLAN:
          TARIFFPLANID: 0
          TARIFFPLAN: TARIFFPLAN
        COMBO_PLANVARIANT:
          TARIFFPLANVARIANT: TARIFFPLANVARIANT
          TARIFFPLANVARIANTID: 6
        COMBO_PRODUCTO:
          PRODUCTO: PRODUCTO
          PRODUCTID: 1
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetBuro_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        BURO:
          $ref: '#/components/schemas/ResponseGetBuro_data_BURO'
      example:
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
        BURO:
          ID: 0
          NAME: NAME
    ResponseGetFormasPago_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        MPAGOS:
          $ref: '#/components/schemas/ResponseGetBuro_data_BURO'
      example:
        MPAGOS:
          ID: 0
          NAME: NAME
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetDiasGozados_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        DIAS_GOZADOS:
          $ref: '#/components/schemas/ResponseGetBuro_data_BURO'
      example:
        errorCode: 0
        DIAS_GOZADOS:
          ID: 0
          NAME: NAME
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetPrecioRegular_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        PRECIO_REGULAR:
          $ref: '#/components/schemas/ResponseGetPrecioRegular_data_PRECIO_REGULAR'
      example:
        PRECIO_REGULAR:
          PRECIO: 0.8008282
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponseGetUpgrade_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: OK
        UPGRADE:
          $ref: '#/components/schemas/ResponseGetUpgrade_data_UPGRADE'
      example:
        UPGRADE:
          PLAN_UPGRADE: PLAN_UPGRADE
          ID: 0
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    ResponsePostDiccionarioDatos_data:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: INGRESO DE DATOS CORRECTO
      example:
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: INGRESO DE DATOS CORRECTO
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
          example: -1
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
        message:
          type: string
          example: mensaje de error
    Upgrade:
      required:
      - Mes Fin UPGRADE
      - Mes Inicio UPGRADE
      - UPGRADE
      properties:
        UPGRADE:
          type: integer
          example: 1000582
        Mes Inicio UPGRADE:
          type: integer
          example: 0
        Mes Fin UPGRADE:
          type: string
          example: 0 - 24 o siempre
    STREAMING:
      type: object
      additionalProperties:
        required:
        - Mes Fin
        - Mes Inicio
        - Paquete
        - Precio Promocional
        - Precio Referencial
        - Producto Adicional
        type: object
        properties:
          Paquete:
            type: integer
            example: 1000569
          Producto Adicional:
            type: string
            example: STREAMING
          Precio Referencial:
            type: number
            format: float
            example: 0
          Precio Promocional:
            type: number
            format: float
            example: 0
          Mes Inicio:
            type: integer
            example: 0
          Mes Fin:
            type: string
            example: SIEMPRE
    TELEFONIA:
      required:
      - Plan
      properties:
        Plan:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/BodyProductoAdicional'
    TELEVISION:
      required:
      - Plan
      properties:
        Plan:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/BodyProductoAdicional'
    ROUTER:
      required:
      - Modelo
      properties:
        Modelo:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/BodyProductoAdicional'
    BodyProductoAdicional:
      required:
      - Cantidad
      - Mes Fin
      - Mes Inicio
      - Precio Promocional
      - Precio Referencial
      - Producto Adicional
      properties:
        Producto Adicional:
          type: string
          example: STREAMING
        Cantidad:
          type: integer
          example: 5
        Precio Referencial:
          type: number
          format: float
          example: 0
        Precio Promocional:
          type: number
          format: float
          example: 0
        Mes Inicio:
          type: integer
          example: 0
        Mes Fin:
          type: string
          example: ' 0 - 24 o SIEMPRE'
    DiccionarioDatos:
      required:
      - Buro
      - Canal
      - Ciudades
      - Dias Gozado
      - Fecha Finalizacion Promocion
      - Fecha Generacion Registro
      - Fecha Inicio Promocion
      - Formas de Pago
      - Id Registro
      - Mes Fin Promocion
      - Mes Inicio Promocion
      - Nombre Promocion
      - Plan_Id
      - Precio Promocional
      - Precio Referencial
      - Producto_Id
      - Sectores
      - Servicio
      - Variant_Id
      properties:
        Id Registro:
          type: integer
          example: 90
        Nombre Promocion:
          type: string
          example: Prueba de Modulos
        Fecha Inicio Promocion:
          type: string
          format: date
          example: 2024-08-08
        Fecha Finalizacion Promocion:
          type: string
          format: date
          example: 2024-08-08
        Servicio:
          type: string
          example: INTERNET
        Plan_Id:
          type: integer
          example: 123322
        Variant_Id:
          type: integer
          example: 123322
        Producto_Id:
          type: integer
          example: 123322
        Dias Gozados:
          type: string
          example: "YES"
          enum:
          - "Yes"
          - "No"
        Canal:
          type: integer
          example: 12
        Precio Promocional:
          type: number
          format: float
          example: 99.99
        Precio Referencial:
          type: number
          format: float
          example: 99.99
        Mes Inicio Promocion:
          type: integer
          example: 24
        Mes Fin Promocion:
          type: string
          example: 0 - 24 o SIEMPRE
        UPGRADE:
          allOf:
          - $ref: '#/components/schemas/Upgrade'
        Ciudades:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Sectores:
          oneOf:
          - type: array
            example:
            - 1
            - 2
            - 3
            items:
              type: integer
          - type: array
            example:
            - TODOS
            items:
              type: string
        Buro:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Formas de Pago:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Fecha Generacion Registro:
          type: string
          format: date-time
        STREAMING:
          allOf:
          - $ref: '#/components/schemas/STREAMING'
        TELEFONIA:
          allOf:
          - $ref: '#/components/schemas/TELEFONIA'
        TELEVISION:
          allOf:
          - $ref: '#/components/schemas/TELEVISION'
        ROUTER:
          allOf:
          - $ref: '#/components/schemas/ROUTER'
    ResponseGetProvincia_data_PROVINCIES:
      type: object
      properties:
        PROVINCIA_ID:
          type: integer
        PROVINCIA:
          type: string
      example:
        PROVINCIA: PROVINCIA
        PROVINCIA_ID: 0
    ResponseGetCiudad_data_CITIES:
      type: object
      properties:
        CIUDAD_ID:
          type: integer
        CIUDAD:
          type: string
        PROVINCIA:
          type: string
      example:
        PROVINCIA: PROVINCIA
        CIUDAD: CIUDAD
        CIUDAD_ID: 0
    ResponseGetSectores_Data_SECTORS:
      type: object
      properties:
        SECTOR_ID:
          type: integer
        SECTOR:
          type: string
        CIUDAD:
          type: string
      example:
        SECTOR: SECTOR
        CIUDAD: CIUDAD
        SECTOR_ID: 0
    ResponseGetPlanes_data_PLANES:
      type: object
      properties:
        TARIFFPLANID:
          type: integer
        TARIFFPLAN:
          type: string
        TARIFFPLANVARIANTID:
          type: integer
        TARIFFPLANVARIANT:
          type: string
      example:
        TARIFFPLANID: 0
        TARIFFPLANVARIANT: TARIFFPLANVARIANT
        TARIFFPLAN: TARIFFPLAN
        TARIFFPLANVARIANTID: 6
    ResponseServicios_data_SERVICIOS:
      type: object
      properties:
        SERVICIOS:
          type: string
      example:
        SERVICIOS: SERVICIOS
    ResponseOfertas_data_OFERTAS:
      type: object
      properties:
        OFERTA_ID:
          type: integer
        OFERTA:
          type: string
      example:
        OFERTA_ID: 0
        OFERTA: OFERTA
    ResponseCombos_data_COMBO_PLAN:
      type: object
      properties:
        TARIFFPLANID:
          type: integer
        TARIFFPLAN:
          type: string
      example:
        TARIFFPLANID: 0
        TARIFFPLAN: TARIFFPLAN
    ResponseCombos_data_COMBO_PLANVARIANT:
      type: object
      properties:
        TARIFFPLANVARIANTID:
          type: integer
        TARIFFPLANVARIANT:
          type: string
      example:
        TARIFFPLANVARIANT: TARIFFPLANVARIANT
        TARIFFPLANVARIANTID: 6
    ResponseCombos_data_COMBO_PRODUCTO:
      type: object
      properties:
        PRODUCTID:
          type: integer
        PRODUCTO:
          type: string
      example:
        PRODUCTO: PRODUCTO
        PRODUCTID: 1
    ResponseGetBuro_data_BURO:
      type: object
      properties:
        ID:
          type: integer
        NAME:
          type: string
      example:
        ID: 0
        NAME: NAME
    ResponseGetPrecioRegular_data_PRECIO_REGULAR:
      type: object
      properties:
        PRECIO:
          type: number
          format: float
      example:
        PRECIO: 0.8008282
    ResponseGetUpgrade_data_UPGRADE:
      type: object
      properties:
        ID:
          type: integer
        PLAN_UPGRADE:
          type: string
      example:
        PLAN_UPGRADE: PLAN_UPGRADE
        ID: 0

