openapi: 3.0.3
info:
  title: Modulo Promocionales MS
  description: Microservicio de Modulos Promocionales
  version: 1.0.11
servers:
- url: /rest/modulos-promocionales-api/v1.0/
tags:
- name: Lugares
  description: "Informacion de Provincias, Ciudades, Sectores y Zonas donde aplican\
    \ los modulos."
- name: Financiero
  description: "Informacion de datos financieron como Modos de Pago, buro, y datos\
    \ promocionales que aplican en los modulos."
- name: Planes
  description: Informacion de datos sobre planes sobre productos de modulos.
- name: Modulo Promocional
  description: Carga de Modulo Promocional
paths:
  /get/Planes:
    post:
      tags:
      - Planes
      description: Consulta de Datos de Provincias segun sus parametros.
      operationId: get_planes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetPlanes'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
        "500":
          description: Internal Error Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
      x-openapi-router-controller: swagger_server.controllers.planes_controller
  /get/Lugares:
    post:
      tags:
      - Lugares
      description: Consulta de Datos de Provincias segun sus parametros.
      operationId: get_lugares
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetLugares'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
        "500":
          description: Internal Error Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
      x-openapi-router-controller: swagger_server.controllers.lugares_controller
  /get/Financiero:
    post:
      tags:
      - Financiero
      operationId: get_financiero
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetFinanciero'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
        "500":
          description: Internal Error Server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              examples:
                request incorrecto:
                  value:
                    codeError: -1
                    internalTransactionId: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
                    externalTransactionId: c5a07d5d-0f84-4ea1-a5b4-a413aa0d21b9
                    message: El Request enviado no es el correcto
      x-openapi-router-controller: swagger_server.controllers.financiero_controller
  /post/modulo-promocional:
    post:
      tags:
      - Modulo Promocional
      operationId: get_modulo_promocional
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResquestPostDiccionarioDatos'
      responses:
        "200":
          description: OK
        "400":
          description: BAD REQUEST
      x-openapi-router-controller: swagger_server.controllers.modulo_promocional_controller
components:
  schemas:
    RequestGetLugares:
      required:
      - channel
      - externalTransactionId
      - type
      properties:
        externalTransactionId:
          type: string
          example: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
        channel:
          type: string
          example: api-modulos-promocionales-lugares
        type:
          type: string
          example: SECTORES_ESPECIFICOSxCITYxTFV
        TARIFFPLANVARIANT:
          type: integer
          example: 0
        PRODUCTOID:
          type: integer
          example: 0
        id_Prov:
          type: integer
          example: 0
        id_Provs:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        id_City:
          type: integer
          example: 0
        id_Cities:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
    RequestGetPlanes:
      required:
      - channel
      - externalTransactionId
      - stype
      - type
      properties:
        externalTransactionId:
          type: string
          example: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
        channel:
          type: string
          example: api-modulos-promocionales-lugares
        type:
          type: string
          example: ALL_DATA O COMBO
        stype:
          type: string
          example: "SERV, OFER"
        SERVICIO:
          type: string
          example: INTERNET
        TIPO_SERVICIO:
          type: string
          example: COORPORATIVO O RESIDENCIAL
    RequestGetFinanciero:
      required:
      - channel
      - externalTransactionId
      - type
      properties:
        externalTransactionId:
          type: string
          example: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
        channel:
          type: string
          example: api-modulos-promocionales-lugares
        type:
          type: string
          example: DIAS_GOZADOS ALL_MPAGOS
        id_Prod:
          type: integer
          example: 0
        TARIFFPLAN:
          type: integer
          example: 0
        TARIFFPLANVARIANT:
          type: integer
          example: 0
    ResquestPostDiccionarioDatos:
      required:
      - channel
      - data
      - externalTransactionId
      properties:
        externalTransactionId:
          type: string
          example: c6ea905e-d77c-45c0-a1ab-8d85d1d1992d
        channel:
          type: string
          example: web-modulos-promocionales
        data:
          $ref: '#/components/schemas/DataPostDiccionarioDatos'
    DataPostDiccionarioDatos:
      required:
      - Buro
      - Canal
      - Ciudades
      - Dias Gozado
      - Fecha Finalizacion Promocion
      - Fecha Generacion Registro
      - Fecha Inicio Promocion
      - Formas de Pago
      - Id Registro
      - Mes Fin Promocion
      - Mes Inicio Promocion
      - Nombre Promocion
      - Plan_Id
      - Precio Promocional
      - Precio Referencial
      - Producto_Id
      - Sectores
      - Servicio
      - Variant_Id
      properties:
        Id Registro:
          type: integer
          example: 90
        Nombre Promocion:
          type: string
          example: Prueba de Modulos
        Fecha Inicio Promocion:
          type: string
          format: date
          example: 2024-08-08
        Fecha Finalizacion Promocion:
          type: string
          format: date
          example: 2024-08-08
        Servicio:
          type: string
          example: INTERNET
        Plan_Id:
          type: integer
          example: 123322
        Variant_Id:
          type: integer
          example: 123322
        Producto_Id:
          type: integer
          example: 123322
        Dias Gozados:
          type: string
          example: "YES"
          enum:
          - "Yes"
          - "No"
        Canal:
          type: integer
          example: 12
        Precio Promocional:
          type: number
          format: float
          example: 99.99
        Precio Referencial:
          type: number
          format: float
          example: 99.99
        Mes Inicio Promocion:
          type: integer
          example: 24
        Mes Fin Promocion:
          type: string
          example: 0 - 24 o SIEMPRE
        UPGRADE:
          allOf:
          - $ref: '#/components/schemas/DataUpgrade'
        Ciudades:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Sectores:
          oneOf:
          - type: array
            example:
            - 1
            - 2
            - 3
            items:
              type: integer
          - type: array
            example:
            - TODOS
            items:
              type: string
        Buro:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Formas de Pago:
          type: array
          example:
          - 96006
          - 96000
          items:
            type: integer
        Fecha Generacion Registro:
          type: string
          format: date-time
        STREAMING:
          allOf:
          - $ref: '#/components/schemas/DataSTREAMING'
        TELEFONIA:
          allOf:
          - $ref: '#/components/schemas/DataTELEFONIA'
        TELEVISION:
          allOf:
          - $ref: '#/components/schemas/DataTELEVISION'
        ROUTER:
          allOf:
          - $ref: '#/components/schemas/DataROUTER'
    DataUpgrade:
      required:
      - Mes Fin UPGRADE
      - Mes Inicio UPGRADE
      - UPGRADE
      properties:
        UPGRADE:
          type: integer
          example: 1000582
        Mes Inicio UPGRADE:
          type: integer
          example: 0
        Mes Fin UPGRADE:
          type: string
          example: 0 - 24 o siempre
    DataSTREAMING:
      type: object
      additionalProperties:
        required:
        - Mes Fin
        - Mes Inicio
        - Paquete
        - Precio Promocional
        - Precio Referencial
        - Producto Adicional
        type: object
        properties:
          Paquete:
            type: integer
            example: 1000569
          Producto Adicional:
            type: string
            example: STREAMING
          Precio Referencial:
            type: number
            format: float
            example: 0
          Precio Promocional:
            type: number
            format: float
            example: 0
          Mes Inicio:
            type: integer
            example: 0
          Mes Fin:
            type: string
            example: SIEMPRE
    DataTELEFONIA:
      required:
      - Plan
      properties:
        Plan:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/ProductoAdicional'
    DataTELEVISION:
      required:
      - Plan
      properties:
        Plan:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/ProductoAdicional'
    DataROUTER:
      required:
      - Modelo
      properties:
        Modelo:
          type: integer
          example: 1000569
      allOf:
      - $ref: '#/components/schemas/ProductoAdicional'
    ProductoAdicional:
      required:
      - Cantidad
      - Mes Fin
      - Mes Inicio
      - Precio Promocional
      - Precio Referencial
      - Producto Adicional
      properties:
        Producto Adicional:
          type: string
          example: STREAMING
        Cantidad:
          type: integer
          example: 5
        Precio Referencial:
          type: number
          format: float
          example: 0
        Precio Promocional:
          type: number
          format: float
          example: 0
        Mes Inicio:
          type: integer
          example: 0
        Mes Fin:
          type: string
          example: ' 0 - 24 o SIEMPRE'
    ResponseGetProvincias:
      type: object
      properties:
        errorCode:
          type: integer
        PROVINCIES:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetProvincias_PROVINCIES'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetCiudades:
      type: object
      properties:
        errorCode:
          type: integer
        CITIES:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetCiudades_CITIES'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetSectores:
      type: object
      properties:
        errorCode:
          type: integer
        SECTORS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetSectores_SECTORS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetCiudadesPorProvincia:
      type: object
      properties:
        errorCode:
          type: integer
        CITIESxPROV:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetCiudades_CITIES'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetSectoresPorCiudad:
      type: object
      properties:
        errorCode:
          type: integer
        SECTORSxCITY:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetSectores_SECTORS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetServicio:
      type: object
      properties:
        errorCode:
          type: integer
        SERVICIOS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetServicio_SERVICIOS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetCombo_Planes:
      type: object
      properties:
        errorCode:
          type: integer
        COMBO_PLAN:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetCombo_Planes_COMBO_PLAN'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetCombo_PlanVariant:
      type: object
      properties:
        errorCode:
          type: integer
        COMBO_PLANVARIANT:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetCombo_PlanVariant_COMBO_PLANVARIANT'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetCombo_Producto:
      type: object
      properties:
        errorCode:
          type: integer
        COMBO_PRODUCTO:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetCombo_Producto_COMBO_PRODUCTO'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetOfertas:
      type: object
      properties:
        errorCode:
          type: integer
        OFERTAS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetOfertas_OFERTAS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetTipo_Servicio:
      type: object
      properties:
        errorCode:
          type: integer
        TIPO_SERVICIO:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetTipo_Servicio_TIPO_SERVICIO'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetTecnologias:
      type: object
      properties:
        errorCode:
          type: integer
        TECNOLOGIAS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetTecnologias_TECNOLOGIAS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetPrecio_Regular:
      type: object
      properties:
        errorCode:
          type: integer
        PRECIO_REGULAR:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetPrecio_Regular_PRECIO_REGULAR'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetDias_Gozados:
      type: object
      properties:
        errorCode:
          type: integer
        DIAS_GOZADOS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetDias_Gozados_DIAS_GOZADOS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetBuro:
      type: object
      properties:
        errorCode:
          type: integer
        BURO:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetBuro_BURO'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetModos_Pago:
      type: object
      properties:
        errorCode:
          type: integer
        MPAGOS:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetModos_Pago_MPAGOS'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseGetUpgrade:
      type: object
      properties:
        errorCode:
          type: integer
        UPGRADE:
          type: array
          items:
            $ref: '#/components/schemas/ResponseGetUpgrade_UPGRADE'
        internalTransactionId:
          type: integer
        externalTransactionId:
          type: integer
        message:
          type: string
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
          example: 0
        message:
          type: string
          example: OK
        internalTransactionId:
          type: string
          example: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId:
          type: string
          example: 82fb166d-c273-4840-9008-c895cf9de255
      example:
        errorCode: 0
        internalTransactionId: 03c33780-88cf-46cf-ba22-925e4d5be471
        externalTransactionId: 82fb166d-c273-4840-9008-c895cf9de255
        message: OK
    inline_response_200:
      oneOf:
      - $ref: '#/components/schemas/ResponseGetOfertas'
      - $ref: '#/components/schemas/ResponseGetTipo_Servicio'
      - $ref: '#/components/schemas/ResponseGetTecnologias'
      - $ref: '#/components/schemas/ResponseGetServicio'
      - $ref: '#/components/schemas/ResponseGetCombo_Planes'
      - $ref: '#/components/schemas/ResponseGetCombo_PlanVariant'
      - $ref: '#/components/schemas/ResponseGetCombo_Producto'
    inline_response_200_1:
      oneOf:
      - $ref: '#/components/schemas/ResponseGetProvincias'
      - $ref: '#/components/schemas/ResponseGetCiudades'
      - $ref: '#/components/schemas/ResponseGetSectores'
      - $ref: '#/components/schemas/ResponseGetCiudadesPorProvincia'
      - $ref: '#/components/schemas/ResponseGetSectoresPorCiudad'
    inline_response_200_2:
      oneOf:
      - $ref: '#/components/schemas/ResponseGetPrecio_Regular'
      - $ref: '#/components/schemas/ResponseGetDias_Gozados'
      - $ref: '#/components/schemas/ResponseGetBuro'
      - $ref: '#/components/schemas/ResponseGetModos_Pago'
      - $ref: '#/components/schemas/ResponseGetUpgrade'
    ResponseGetProvincias_PROVINCIES:
      type: object
      properties:
        PROVINCIA:
          type: string
        PROVINCIA_ID:
          type: integer
    ResponseGetCiudades_CITIES:
      type: object
      properties:
        CIUDAD:
          type: string
        CIUDAD_ID:
          type: integer
        PROVINCIA:
          type: string
    ResponseGetSectores_SECTORS:
      type: object
      properties:
        CIUDAD:
          type: string
        SECTOR:
          type: string
        SECTOR_ID:
          type: integer
    ResponseGetServicio_SERVICIOS:
      type: object
      properties:
        SERVICIOS:
          type: string
    ResponseGetCombo_Planes_COMBO_PLAN:
      type: object
      properties:
        TARIFFPLAN:
          type: string
        TARIFFPLANID:
          type: integer
    ResponseGetCombo_PlanVariant_COMBO_PLANVARIANT:
      type: object
      properties:
        TARIFFPLANVARIANT:
          type: string
          example: X-Futbol Standard HFC
        TARIFFPLANVARIANTID:
          type: integer
          example: 1000632
    ResponseGetCombo_Producto_COMBO_PRODUCTO:
      type: object
      properties:
        PRODUCTO:
          type: string
          example: X-Futbol Standard HFC
        PRODUCTID:
          type: integer
          example: 1000632
    ResponseGetOfertas_OFERTAS:
      type: object
      properties:
        OFERTA_ID:
          type: integer
          example: 9
        OFERTA:
          type: string
          example: PAPA
    ResponseGetTipo_Servicio_TIPO_SERVICIO:
      type: object
      properties:
        TIPO_SERVICIO:
          type: string
          example: COORPORATIVO
    ResponseGetTecnologias_TECNOLOGIAS:
      type: object
      properties:
        TECNOLOGIA:
          type: string
          example: HFC
    ResponseGetPrecio_Regular_PRECIO_REGULAR:
      type: object
      properties:
        PRECIO:
          type: number
          format: float
          example: 99.99
    ResponseGetDias_Gozados_DIAS_GOZADOS:
      type: object
      properties:
        NAME:
          type: string
          example: "YES"
        ID:
          type: integer
          example: 1000632
    ResponseGetBuro_BURO:
      type: object
      properties:
        NAME:
          type: string
          example: A
        ID:
          type: integer
          example: 1000632
    ResponseGetModos_Pago_MPAGOS:
      type: object
      properties:
        NAME:
          type: string
          example: Efectivo
        ID:
          type: integer
          example: 500076
    ResponseGetUpgrade_UPGRADE:
      type: object
      properties:
        PLAN_UPGRADE:
          type: string
          example: Turbo(300 MB)
        ID:
          type: integer
          example: 1000577

